-- ============================================================
-- Workout Service (v1) - Offline-first, simple schema
-- PostgreSQL 13+
-- Schema: workout
--
-- Design principles:
--   - Client generates all UUIDs → upsert is idempotent
--   - workout_session saved as a complete object (sync model)
--   - session detail stored as JSONB (arrives whole, no partial updates)
--   - Multilingua only on workout title/description (JSONB)
--   - exercise_id is an opaque external ref to catalog-service
--   - user_id is an opaque external ref to user-profile-be
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE SCHEMA IF NOT EXISTS workout;
COMMENT ON SCHEMA workout IS
    'Workout service schema. Manages workout templates (schema) and '
        'executed sessions (offline-first, synced as complete objects).';

-- ============================================================
-- ENUMs
-- ============================================================

DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
                       WHERE n.nspname = 'workout' AND t.typname = 'workout_status') THEN
            CREATE TYPE workout.workout_status AS ENUM ('draft', 'active', 'archived');
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
                       WHERE n.nspname = 'workout' AND t.typname = 'session_status') THEN
            CREATE TYPE workout.session_status AS ENUM ('in_progress', 'completed', 'abandoned');
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
                       WHERE n.nspname = 'workout' AND t.typname = 'set_type') THEN
            CREATE TYPE workout.set_type AS ENUM (
                'normal',       -- serie standard
                'warmup',       -- riscaldamento
                'approach',     -- avvicinamento al carico
                'dropset',      -- riduzione carico senza riposo
                'cluster',      -- microriposi intra-serie
                'failure',      -- portata a cedimento
                'rest_pause',   -- riposo breve + ulteriori reps
                'amrap'         -- as many reps as possible
                );
        END IF;

        IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
                       WHERE n.nspname = 'workout' AND t.typname = 'load_unit') THEN
            CREATE TYPE workout.load_unit AS ENUM ('kg', 'lbs', 'bodyweight', 'band', 'machine_notch');
        END IF;
    END$$;

-- ============================================================
-- Utility: updated_at trigger
-- ============================================================

CREATE OR REPLACE FUNCTION workout.tg_set_updated_at()
    RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := NOW();
    RETURN NEW;
END;
$$;

-- ============================================================
-- Table: workout
-- ============================================================
-- The "schema" / template created by the user.
-- Multilingua on title and description via JSONB (same pattern
-- as exercise catalog). Canonical title in the 'name' column
-- for fast search; translations for localized display.
--
-- translations JSONB structure:
-- {
--   "it": { "title": "...", "description": "..." },
--   "en": { "title": "...", "description": "..." }
-- }
-- ============================================================

CREATE TABLE IF NOT EXISTS workout.workout (
                                               id              UUID            PRIMARY KEY,  -- generated by client

                                               user_id         UUID            NOT NULL,     -- opaque ref to user-profile-be
                                               name            VARCHAR(255)    NOT NULL,      -- canonical (fallback) title, always present
                                               translations    JSONB           NOT NULL DEFAULT '{}',

                                               status          workout.workout_status  NOT NULL DEFAULT 'active',
                                               deleted_at      TIMESTAMPTZ,                  -- soft delete

                                               created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
                                               updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

                                               CONSTRAINT chk_workout_name_nonempty CHECK (LENGTH(TRIM(name)) > 0)
);

COMMENT ON TABLE  workout.workout IS
    'Workout template created by a user. Contains blocks and sets as child rows. '
        'Multilingua on title/description via translations JSONB.';
COMMENT ON COLUMN workout.workout.id IS
    'UUID generated by the client. Enables offline creation and idempotent sync.';
COMMENT ON COLUMN workout.workout.user_id IS
    'Opaque external reference to user-profile-be. No FK by design (cross-service).';
COMMENT ON COLUMN workout.workout.name IS
    'Canonical title (fallback). Always present, used for search.';
COMMENT ON COLUMN workout.workout.translations IS
    'Per-language title and description: {"it": {"title": "...", "description": "..."}, ...}';

DROP TRIGGER IF EXISTS trg_workout_set_updated_at ON workout.workout;
CREATE TRIGGER trg_workout_set_updated_at
    BEFORE UPDATE ON workout.workout
    FOR EACH ROW EXECUTE FUNCTION workout.tg_set_updated_at();

CREATE INDEX IF NOT EXISTS idx_workout_user
    ON workout.workout (user_id)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_workout_name_trgm
    ON workout.workout USING GIN (name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_workout_translations_gin
    ON workout.workout USING GIN (translations);

-- ============================================================
-- Table: workout_block
-- ============================================================
-- An ordered group of exercises. 1 entry = normal set.
-- 2+ entries = superset (executed in sequence A→B→A→B).
-- rest_seconds is the rest AFTER completing all sets of the block.
-- ============================================================

CREATE TABLE IF NOT EXISTS workout.workout_block (
                                                     id              UUID            PRIMARY KEY,  -- generated by client
                                                     workout_id      UUID            NOT NULL REFERENCES workout.workout(id) ON DELETE CASCADE,

                                                     position        SMALLINT        NOT NULL,     -- order within the workout (0-based)
                                                     label           VARCHAR(50),                  -- optional UI label, e.g. "A", "Superset 1"
                                                     rest_seconds    SMALLINT,                     -- rest after completing all sets of this block
                                                     notes           TEXT,

                                                     created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
                                                     updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

                                                     CONSTRAINT uq_workout_block_position UNIQUE (workout_id, position),
                                                     CONSTRAINT chk_rest_seconds CHECK (rest_seconds IS NULL OR rest_seconds >= 0)
);

COMMENT ON TABLE  workout.workout_block IS
    'Ordered block within a workout. Holds one or more entries (superset if >1).';
COMMENT ON COLUMN workout.workout_block.position IS
    '0-based order within the workout. Client manages ordering.';
COMMENT ON COLUMN workout.workout_block.rest_seconds IS
    'Rest time after completing all sets of this block (seconds).';

DROP TRIGGER IF EXISTS trg_workout_block_set_updated_at ON workout.workout_block;
CREATE TRIGGER trg_workout_block_set_updated_at
    BEFORE UPDATE ON workout.workout_block
    FOR EACH ROW EXECUTE FUNCTION workout.tg_set_updated_at();

CREATE INDEX IF NOT EXISTS idx_workout_block_workout
    ON workout.workout_block (workout_id);

-- ============================================================
-- Table: workout_block_entry
-- ============================================================
-- One exercise slot inside a block.
-- Single entry = normal. Multiple entries = superset.
-- ============================================================

CREATE TABLE IF NOT EXISTS workout.workout_block_entry (
                                                           id              UUID            PRIMARY KEY,  -- generated by client
                                                           block_id        UUID            NOT NULL REFERENCES workout.workout_block(id) ON DELETE CASCADE,

                                                           exercise_id     UUID            NOT NULL,     -- opaque ref to catalog-service exercise
                                                           position        SMALLINT        NOT NULL,     -- order within the block (superset order)

                                                           created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
                                                           updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

                                                           CONSTRAINT uq_block_entry_position UNIQUE (block_id, position)
);

COMMENT ON TABLE  workout.workout_block_entry IS
    'One exercise slot inside a block. >1 entry in same block = superset.';
COMMENT ON COLUMN workout.workout_block_entry.exercise_id IS
    'Opaque external reference to exercises.exercise in catalog-service.';
COMMENT ON COLUMN workout.workout_block_entry.position IS
    '0-based order within the block. Defines superset sequence.';

DROP TRIGGER IF EXISTS trg_workout_block_entry_set_updated_at ON workout.workout_block_entry;
CREATE TRIGGER trg_workout_block_entry_set_updated_at
    BEFORE UPDATE ON workout.workout_block_entry
    FOR EACH ROW EXECUTE FUNCTION workout.tg_set_updated_at();

CREATE INDEX IF NOT EXISTS idx_workout_block_entry_block
    ON workout.workout_block_entry (block_id);

CREATE INDEX IF NOT EXISTS idx_workout_block_entry_exercise
    ON workout.workout_block_entry (exercise_id);

-- ============================================================
-- Table: workout_set
-- ============================================================
-- A single planned set row for one entry.
-- This is what the user sees in the template: "3x10 @ 80kg"
-- ============================================================

CREATE TABLE IF NOT EXISTS workout.workout_set (
                                                   id              UUID            PRIMARY KEY,  -- generated by client
                                                   entry_id        UUID            NOT NULL REFERENCES workout.workout_block_entry(id) ON DELETE CASCADE,

                                                   position        SMALLINT        NOT NULL,     -- set number within the entry (0-based)
                                                   set_type        workout.set_type  NOT NULL DEFAULT 'normal',

                                                   reps            SMALLINT,                     -- planned reps (null = open / AMRAP)
                                                   load            NUMERIC(6, 2),                -- planned load
                                                   load_unit       workout.load_unit  NOT NULL DEFAULT 'kg',
                                                   rest_seconds    SMALLINT,                     -- rest after THIS set (overrides block rest)

                                                   notes           TEXT,

                                                   created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
                                                   updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

                                                   CONSTRAINT uq_workout_set_position     UNIQUE (entry_id, position),
                                                   CONSTRAINT chk_workout_set_reps        CHECK (reps IS NULL OR reps > 0),
                                                   CONSTRAINT chk_workout_set_load        CHECK (load IS NULL OR load >= 0),
                                                   CONSTRAINT chk_workout_set_rest        CHECK (rest_seconds IS NULL OR rest_seconds >= 0)
);

COMMENT ON TABLE  workout.workout_set IS
    'A single planned set row within a workout entry. '
        'Represents one "line" in the workout template (e.g. 3x10 @ 80kg).';
COMMENT ON COLUMN workout.workout_set.reps IS
    'Planned reps. NULL = open/AMRAP (use set_type=amrap to signal intent).';
COMMENT ON COLUMN workout.workout_set.rest_seconds IS
    'Rest after this specific set. If set, overrides the block-level rest_seconds.';

DROP TRIGGER IF EXISTS trg_workout_set_set_updated_at ON workout.workout_set;
CREATE TRIGGER trg_workout_set_set_updated_at
    BEFORE UPDATE ON workout.workout_set
    FOR EACH ROW EXECUTE FUNCTION workout.tg_set_updated_at();

CREATE INDEX IF NOT EXISTS idx_workout_set_entry
    ON workout.workout_set (entry_id);

-- ============================================================
-- Table: workout_session
-- ============================================================
-- The execution of a workout. Saved as a complete snapshot
-- from the client (offline-first sync model).
--
-- snapshot JSONB contains the full denormalized session structure:
-- {
--   "workout_name": "...",
--   "blocks": [
--     {
--       "source_block_id": "uuid|null",   -- null if added live
--       "label": "A",
--       "position": 0,
--       "entries": [
--         {
--           "source_entry_id": "uuid|null",
--           "exercise_id": "uuid",
--           "exercise_name": "Panca Piana",  -- denormalized for offline display
--           "position": 0,
--           "sets": [
--             {
--               "source_set_id": "uuid|null",
--               "position": 0,
--               "set_type": "normal",
--               "planned_reps": 10,
--               "planned_load": 80.0,
--               "load_unit": "kg",
--               "actual_reps": 10,
--               "actual_load": 82.5,
--               "completed": true,
--               "skipped": false,
--               "rest_seconds": 90,
--               "notes": "sentita bene"
--             }
--           ]
--         }
--       ]
--     }
--   ]
-- }
--
-- source_*_id = null → set/entry/block added by user during the session
-- ============================================================

CREATE TABLE IF NOT EXISTS workout.workout_session (
                                                       id                  UUID        PRIMARY KEY,  -- generated by client
                                                       user_id             UUID        NOT NULL,     -- opaque ref to user-profile-be
                                                       workout_id          UUID,                     -- opaque ref to source workout (null = free session)

                                                       status              workout.session_status  NOT NULL DEFAULT 'in_progress',

                                                       started_at          TIMESTAMPTZ NOT NULL,     -- set by client (offline-aware)
                                                       ended_at            TIMESTAMPTZ,              -- set on complete/abandon
                                                       duration_seconds    INT,                      -- client-computed total duration

    -- Full denormalized session snapshot (see structure above)
                                                       snapshot            JSONB       NOT NULL DEFAULT '{}',

    -- Quick-access stats (extracted from snapshot at sync time, avoid full JSONB scan)
                                                       total_sets          SMALLINT    NOT NULL DEFAULT 0,
                                                       completed_sets      SMALLINT    NOT NULL DEFAULT 0,
                                                       total_volume_kg     NUMERIC(10, 2),           -- sum(actual_reps * actual_load in kg)

                                                       notes               TEXT,                     -- overall session notes

                                                       synced_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),  -- last successful sync
                                                       created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                                                       updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

                                                       CONSTRAINT chk_session_ended_after_started
                                                           CHECK (ended_at IS NULL OR ended_at >= started_at),
                                                       CONSTRAINT chk_session_duration
                                                           CHECK (duration_seconds IS NULL OR duration_seconds >= 0),
                                                       CONSTRAINT chk_completed_sets
                                                           CHECK (completed_sets <= total_sets)
);

COMMENT ON TABLE  workout.workout_session IS
    'Execution of a workout. Saved as a complete object from the client (offline-first). '
        'Upsert on sync using client-generated UUID as idempotency key.';
COMMENT ON COLUMN workout.workout_session.id IS
    'UUID generated by the client before the session starts. '
        'Used as idempotency key for upsert on sync.';
COMMENT ON COLUMN workout.workout_session.workout_id IS
    'Source workout template. NULL for free/unplanned sessions.';
COMMENT ON COLUMN workout.workout_session.snapshot IS
    'Full denormalized session structure. Contains all blocks, entries and sets '
        'with planned vs actual values and completion flags. See table comment for structure.';
COMMENT ON COLUMN workout.workout_session.total_sets IS
    'Total sets in the session (extracted from snapshot at sync time).';
COMMENT ON COLUMN workout.workout_session.completed_sets IS
    'Completed sets (extracted from snapshot at sync time). Used for quick progress queries.';
COMMENT ON COLUMN workout.workout_session.total_volume_kg IS
    'Sum of (actual_reps * actual_load converted to kg) across all completed sets. '
        'Pre-computed at sync time to avoid scanning the snapshot JSONB for stats queries.';
COMMENT ON COLUMN workout.workout_session.synced_at IS
    'Last time the client successfully synced this session. '
        'Useful to detect stale or missing syncs.';
COMMENT ON COLUMN workout.workout_session.started_at IS
    'Session start timestamp as recorded by the client (not server time).';

DROP TRIGGER IF EXISTS trg_workout_session_set_updated_at ON workout.workout_session;
CREATE TRIGGER trg_workout_session_set_updated_at
    BEFORE UPDATE ON workout.workout_session
    FOR EACH ROW EXECUTE FUNCTION workout.tg_set_updated_at();

-- Hot paths
CREATE INDEX IF NOT EXISTS idx_session_user_started
    ON workout.workout_session (user_id, started_at DESC);

CREATE INDEX IF NOT EXISTS idx_session_workout
    ON workout.workout_session (workout_id)
    WHERE workout_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_session_status
    ON workout.workout_session (status)
    WHERE status = 'in_progress';

-- GIN for JSONB queries (exercise_id lookups inside snapshot for PR computation)
CREATE INDEX IF NOT EXISTS idx_session_snapshot_gin
    ON workout.workout_session USING GIN (snapshot);

-- ============================================================
-- View: v_workout_full (workout with block/entry/set count)
-- ============================================================

CREATE OR REPLACE VIEW workout.v_workout_full AS
SELECT
    w.id,
    w.user_id,
    w.name,
    w.translations,
    w.status,
    w.created_at,
    w.updated_at,
    COUNT(DISTINCT b.id)    AS block_count,
    COUNT(DISTINCT e.id)    AS entry_count,
    COUNT(DISTINCT s.id)    AS set_count
FROM      workout.workout              w
              LEFT JOIN workout.workout_block        b ON b.workout_id  = w.id
              LEFT JOIN workout.workout_block_entry  e ON e.block_id    = b.id
              LEFT JOIN workout.workout_set          s ON s.entry_id    = e.id
WHERE w.deleted_at IS NULL
GROUP BY w.id, w.user_id, w.name, w.translations, w.status, w.created_at, w.updated_at;

COMMENT ON VIEW workout.v_workout_full IS
    'Workout with aggregated block/entry/set counts. Use for list views.';

-- ============================================================
-- View: v_session_summary (per user stats)
-- ============================================================

CREATE OR REPLACE VIEW workout.v_session_summary AS
SELECT
    user_id,
    COUNT(*)                                            AS total_sessions,
    COUNT(*) FILTER (WHERE status = 'completed')        AS completed_sessions,
    COUNT(*) FILTER (WHERE status = 'abandoned')        AS abandoned_sessions,
    SUM(total_volume_kg)                                AS total_volume_kg,
    SUM(duration_seconds)                               AS total_duration_seconds,
    MAX(started_at)                                     AS last_session_at
FROM workout.workout_session
GROUP BY user_id;

COMMENT ON VIEW workout.v_session_summary IS
    'Aggregated session stats per user. Used for profile/dashboard.';

-- ============================================================
-- Table summary
-- ============================================================
-- workout.workout               Template created by user (multilingua)
-- workout.workout_block         Ordered block (1 entry = normal, N = superset)
-- workout.workout_block_entry   Exercise slot inside a block
-- workout.workout_set           Planned set row (reps, load, type, rest)
-- workout.workout_session       Executed session (offline-first, snapshot JSONB)
--
-- Offline-first sync contract:
--   - Client generates UUIDs for all entities before going offline
--   - Sync = UPSERT on primary key (idempotent)
--   - workout_session saved as a complete object (no partial row updates)
--   - snapshot JSONB contains the full denormalized session
--   - Quick-access stats (total_sets, completed_sets, total_volume_kg)
--     extracted from snapshot at sync time by the service layer
--
-- Cross-service references (opaque UUIDs, no DB foreign keys):
--   - workout.user_id           → user-profile-be
--   - workout_session.user_id   → user-profile-be
--   - workout_block_entry.exercise_id → catalog-service
--   - snapshot[].entries[].exercise_id → catalog-service
-- ============================================================
