package it.aredegalli.coachly.workout.model;

import it.aredegalli.coachly.workout.enums.WorkoutStatus;
import it.aredegalli.coachly.workout.model.converter.WorkoutStatusConverter;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.SQLRestriction;
import org.hibernate.type.SqlTypes;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Workout template created by a user.
 *
 * <p><strong>Offline-first:</strong> the UUID is generated by the client
 * before the entity exists on the server. Persistence is always via upsert —
 * never rely on server-side ID generation for this entity.
 *
 * <p>Multilingua is handled via {@link #translations} JSONB:
 * <pre>{@code
 * {
 *   "it": { "title": "Forza Upper Body", "description": "..." },
 *   "en": { "title": "Upper Body Strength", "description": "..." }
 * }
 * }</pre>
 *
 * <p>{@link #name} is the canonical (fallback) title, always present,
 * used for full-text search via trigram index.
 *
 * <p>Soft-deleted rows are filtered automatically by {@code @SQLRestriction}.
 */
@Entity
@Table(schema = "workout", name = "workout")
@SQLRestriction("deleted_at IS NULL")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Workout {

    /**
     * Client-generated UUID. Never use {@code @GeneratedValue} here —
     * the ID must be stable before the entity reaches the server.
     */
    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /**
     * Opaque external reference to user-profile-be.
     * No {@code @ManyToOne} — cross-service FK by design.
     */
    @Column(name = "user_id", nullable = false, updatable = false)
    private UUID userId;

    /**
     * Canonical title, always present. Used as fallback when a translation
     * for the requested locale is not available, and for trigram search.
     */
    @Column(name = "name", nullable = false, length = 255)
    private String name;

    /**
     * Per-language title and description.
     * Structure: {@code {"it": {"title": "...", "description": "..."}, "en": {...}}}
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "translations", nullable = false, columnDefinition = "jsonb")
    private String translations;

    @Convert(converter = WorkoutStatusConverter.class)
    @Column(name = "status", nullable = false, length = 20)
    private WorkoutStatus status;

    /** Soft delete timestamp. Set externally; filtered by @SQLRestriction. */
    @Column(name = "deleted_at")
    private OffsetDateTime deletedAt;

    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    // ── Relations ────────────────────────────────────────────

    /**
     * Ordered blocks belonging to this workout.
     * Loaded lazily — use explicit fetch joins when needed.
     */
    @OneToMany(mappedBy = "workout", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @OrderBy("position ASC")
    @Builder.Default
    private List<WorkoutBlock> blocks = new ArrayList<>();

    // ── Lifecycle hooks ──────────────────────────────────────

    @PrePersist
    protected void onCreate() {
        OffsetDateTime now = OffsetDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
        if (this.status == null) {
            this.status = WorkoutStatus.ACTIVE;
        }
        if (this.translations == null) {
            this.translations = "{}";
        }
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }
}
